import { create } from 'zustand';

export const translations = {
  en: {
    welcome: 'Welcome',
    giftLists: 'Gift Lists',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    noAccount: "Don't have an account? Sign up",
    haveAccount: 'Already have an account? Sign in',
    enterName: 'Enter your name',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    createList: 'Create New List',
    joinList: 'Join Existing List',
    openList: 'Open List',
    switchList: 'Switch List',
    yourLists: 'Your Lists',
    listName: 'List Name',
    description: 'Description',
    optional: 'Optional',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    deleteGift: 'Delete Gift',
    editGift: 'Edit Gift',
    newGift: 'New Gift',
    productUrl: 'Product URL',
    pasteUrl: 'Paste product URL',
    giftName: 'Gift Name',
    whatsTheGift: "What's the gift?",
    for: 'For',
    whoIsItFor: 'Who is it for?',
    notes: 'Notes',
    anyNotes: 'Any additional notes?',
    addGift: 'Add Gift',
    viewProduct: 'View Product',
    buyIt: 'Buy it!',
    seeItem: 'See item',
    noLink: 'No purchase link available',
    allStatus: 'All Status',
    purchased: 'Purchased',
    notPurchased: 'Not Purchased',
    allPeople: 'All People',
    shareList: 'Share List',
    copied: 'Copied!',
    joinMe: 'Hey! Join me in my gift list',
    toJoin: 'To join, you\'ll need',
    clickToJoin: 'Click here to join',
    noPresents: 'No Presents Yet',
    startAdding: 'Start adding presents to create your family & friends wishlist'
  },
  es: {
    welcome: 'Bienvenido',
    giftLists: 'Listas de Regalos',
    name: 'Nombre',
    email: 'Correo',
    password: 'Contraseña',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    signOut: 'Cerrar Sesión',
    noAccount: '¿No tienes cuenta? Regístrate',
    haveAccount: '¿Ya tienes cuenta? Inicia sesión',
    enterName: 'Ingresa tu nombre',
    enterEmail: 'Ingresa tu correo',
    enterPassword: 'Ingresa tu contraseña',
    createList: 'Crear Nueva Lista',
    joinList: 'Unirse a Lista',
    openList: 'Abrir Lista',
    switchList: 'Cambiar Lista',
    yourLists: 'Tus Listas',
    listName: 'Nombre de Lista',
    description: 'Descripción',
    optional: 'Opcional',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    deleteGift: 'Eliminar Regalo',
    editGift: 'Editar Regalo',
    newGift: 'Nuevo Regalo',
    productUrl: 'URL del Producto',
    pasteUrl: 'Pega la URL del producto',
    giftName: 'Nombre del Regalo',
    whatsTheGift: '¿Qué es el regalo?',
    for: 'Para',
    whoIsItFor: '¿Para quién es?',
    notes: 'Notas',
    anyNotes: '¿Alguna nota adicional?',
    addGift: 'Agregar Regalo',
    viewProduct: 'Ver Producto',
    buyIt: '¡Comprarlo!',
    seeItem: 'Ver item',
    noLink: 'No hay enlace de compra disponible',
    allStatus: 'Todos los Estados',
    purchased: 'Comprado',
    notPurchased: 'No Comprado',
    allPeople: 'Todas las Personas',
    shareList: 'Compartir Lista',
    copied: '¡Copiado!',
    joinMe: '¡Hey! Únete a mi lista de regalos',
    toJoin: 'Para unirte, necesitarás',
    clickToJoin: 'Haz clic aquí para unirte',
    noPresents: 'No Hay Regalos Aún',
    startAdding: 'Comienza a agregar regalos para crear tu lista de deseos'
  }
};

type Language = 'en' | 'es';

interface LanguageStore {
  language: Language;
  setLanguage: (language: Language) => void;
}

export const useLanguageStore = create<LanguageStore>((set) => ({
  language: 'en',
  setLanguage: (language) => set({ language })
}));